# Generated by Django 5.0.7 on 2024-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_address_address_address_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
