# Generated by Django 5.0.7 on 2024-08-02 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='user_cart',
        ),
    ]
