# Generated by Django 5.1 on 2024-08-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='last_name',
        ),
    ]
