# Generated by Django 5.1 on 2024-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_first_name_contacts_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
