# Generated by Django 5.0.7 on 2024-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_contacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
