# Generated by Django 5.0.6 on 2024-07-13 16:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
