# Generated by Django 5.0.6 on 2024-07-13 16:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0011_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
