# Generated by Django 5.0.6 on 2024-07-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0014_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='blank-sm.png', upload_to='uploads/products'),
        ),
    ]
