# Generated by Django 5.0.6 on 2024-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='blank-sm.png', null=True, upload_to='uploads/products'),
        ),
    ]
