# Generated by Django 5.0.6 on 2024-07-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecom_admin', '0020_alter_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default='4', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
