# Generated by Django 5.0.7 on 2024-07-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0026_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
