# Generated by Django 5.0.7 on 2024-08-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0027_remove_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
