# Generated by Django 5.1 on 2024-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0028_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.BooleanField(default=True)),
                ('slide1_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('slide1_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('slide1_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('slide1_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('slide1_button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('slide2_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('slide2_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('slide2_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('slide2_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('slide2_button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('special_offer_banner1_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('special_offer_banner1_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner1_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner1_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner2_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('special_offer_banner2_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner2_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner2_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner3_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('special_offer_banner3_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner3_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_banner3_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('special_offer_button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('tranding_section', models.BooleanField(default=True)),
                ('tranding_banner', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('tranding_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('tranding_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('tranding_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('tranding_button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('special_offer_banner', models.BooleanField(default=True)),
                ('new_arrival1_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('new_arrival1_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('new_arrival1_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('new_arrival1_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('new_arrival1_button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('new_arrival2_image', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('new_arrival2_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('new_arrival2_secondary_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('new_arrival2_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('new_arrival2_button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('trust_box', models.BooleanField(default=True)),
                ('trust_box1_icon', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('trust_box1_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('trust_box1_secondary_text', models.CharField(blank=True, max_length=600, null=True)),
                ('trust_box2_icon', models.ImageField(blank=True, default='blank-sm.png', null=True, upload_to='')),
                ('trust_box2_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('trust_box2_secondary_text', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
