# Generated by Django 5.1 on 2024-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0029_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='new_arrival1_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='new_arrival2_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slide1_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slide2_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='special_offer_banner1_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='special_offer_banner2_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='special_offer_banner3_image',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tranding_banner',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_box1_icon',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_box2_icon',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
    ]
