# Generated by Django 5.1 on 2024-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0030_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='new_arrival',
            field=models.BooleanField(default=True),
        ),
    ]
