# Generated by Django 5.1 on 2024-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0031_homepage_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='special_offer_button_link2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='special_offer_button_link3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
