# Generated by Django 5.1 on 2024-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0032_homepage_special_offer_button_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='special_offer_button_link1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
