# Generated by Django 5.1 on 2024-08-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0033_homepage_special_offer_button_link1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='special_offer_button_link',
        ),
    ]
