# Generated by Django 5.1 on 2024-08-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0034_remove_homepage_special_offer_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='trust_box3_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_box3_icon',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_box3_secondary_text',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
