# Generated by Django 5.1 on 2024-08-25 10:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0035_homepage_trust_box3_heading_homepage_trust_box3_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=500)),
                ('secendary_title', models.CharField(max_length=500)),
                ('page_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('page_content', tinymce.models.HTMLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=500)),
                ('secendary_title', models.CharField(max_length=500)),
                ('page_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('page_content', tinymce.models.HTMLField(blank=True, default='', null=True)),
            ],
        ),
    ]
