# Generated by Django 5.1 on 2024-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0036_aboutpage_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='page_banner',
            field=models.ImageField(blank=True, default=True, null=True, upload_to=''),
        ),
    ]
