# Generated by Django 5.1 on 2024-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0037_alter_aboutpage_page_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='page_banner',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
    ]
