# Generated by Django 5.1 on 2024-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0038_alter_aboutpage_page_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='page_banner',
            field=models.ImageField(blank=True, default='blank-landscape.jpg', null=True, upload_to=''),
        ),
    ]
