# Generated by Django 5.0.7 on 2024-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0041_privacypolicypage_termspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('method', models.CharField(max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('free_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
