# Generated by Django 5.0.7 on 2024-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0042_shippingzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzone',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='free_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
