# Generated by Django 5.0.7 on 2024-09-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0043_alter_shippingzone_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
