# Generated by Django 5.0.7 on 2024-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0044_shippingzone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_tagline', models.CharField(max_length=255)),
                ('site_description', models.TextField()),
                ('store_address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('admin_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('store_country', models.CharField(choices=[('USA', 'United States'), ('EUR', 'European Union'), ('GBR', 'United Kingdom'), ('BGD', 'Bangladesh')], default='USA', max_length=3)),
                ('store_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('BDT', 'BDT')], default='USD', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
            ],
        ),
    ]
