# Generated by Django 5.0.7 on 2024-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0046_alter_settings_options_alter_settings_store_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='copyright',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='store_currency',
            field=models.CharField(choices=[('$', 'USD - United States Dollar ($)'), ('€', 'EUR - Euro (€)'), ('£', 'GBP - British Pound Sterling (£)'), ('¥', 'JPY - Japanese Yen (¥)'), ('A$', 'AUD - Australian Dollar (A$)'), ('C$', 'CAD - Canadian Dollar (C$)'), ('CHF', 'CHF - Swiss Franc (CHF)'), ('¥', 'CNY - Chinese Yuan (¥)'), ('HK$', 'HKD - Hong Kong Dollar (HK$)'), ('NZ$', 'NZD - New Zealand Dollar (NZ$)'), ('kr', 'SEK - Swedish Krona (kr)'), ('₩', 'KRW - South Korean Won (₩)'), ('S$', 'SGD - Singapore Dollar (S$)'), ('kr', 'NOK - Norwegian Krone (kr)'), ('$', 'MXN - Mexican Peso ($)'), ('₹', 'INR - Indian Rupee (₹)'), ('₽', 'RUB - Russian Ruble (₽)'), ('R', 'ZAR - South African Rand (R)'), ('₺', 'TRY - Turkish Lira (₺)'), ('R$', 'BRL - Brazilian Real (R$)'), ('NT$', 'TWD - New Taiwan Dollar (NT$)'), ('kr', 'DKK - Danish Krone (kr)'), ('zł', 'PLN - Polish Złoty (zł)'), ('฿', 'THB - Thai Baht (฿)'), ('Rp', 'IDR - Indonesian Rupiah (Rp)'), ('Ft', 'HUF - Hungarian Forint (Ft)'), ('Kč', 'CZK - Czech Koruna (Kč)'), ('₪', 'ILS - Israeli New Shekel (₪)'), ('$', 'CLP - Chilean Peso ($)'), ('₱', 'PHP - Philippine Peso (₱)'), ('د.إ', 'AED - United Arab Emirates Dirham (د.إ)'), ('$', 'COP - Colombian Peso ($)'), ('﷼', 'SAR - Saudi Riyal (﷼)'), ('RM', 'MYR - Malaysian Ringgit (RM)'), ('lei', 'RON - Romanian Leu (lei)'), ('$', 'ARS - Argentine Peso ($)'), ('֏', 'AMD - Armenian Dram (֏)'), ('₼', 'AZN - Azerbaijani Manat (₼)'), ('৳', 'BDT - Bangladeshi Taka (৳)'), ('$', 'BSD - Bahamian Dollar ($)'), ('$', 'BBD - Barbadian Dollar ($)'), ('Br', 'BYN - Belarusian Ruble (Br)'), ('$', 'BZD - Belize Dollar ($)'), ('₣', 'BIF - Burundian Franc (₣)'), ('$', 'BMD - Bermudian Dollar ($)'), ('$', 'BND - Brunei Dollar ($)'), ('$', 'BOV - Bolivian Mvdol ($)'), ('$', 'BOB - Bolivian Boliviano ($)'), ('KM', 'BAM - Bosnia and Herzegovina Convertible Mark (KM)'), ('P', 'BWP - Botswana Pula (P)'), ('₣', 'BIF - Burundian Franc (₣)'), ('$', 'KYD - Cayman Islands Dollar ($)'), ('FC', 'CDF - Congolese Franc (FC)'), ('$', 'FJD - Fijian Dollar ($)'), ('L', 'HNL - Honduran Lempira (L)'), ('$', 'TTD - Trinidad and Tobago Dollar ($)'), ('$', 'XCD - East Caribbean Dollar ($)'), ('$', 'GIP - Gibraltar Pound (£)'), ('₣', 'GNF - Guinean Franc (₣)'), ('Q', 'GTQ - Guatemalan Quetzal (Q)'), ('$', 'GYD - Guyanese Dollar ($)'), ('$', 'JMD - Jamaican Dollar ($)'), ('L', 'HNL - Honduran Lempira (L)'), ('$', 'XCD - East Caribbean Dollar ($)'), ('$', 'SBD - Solomon Islands Dollar ($)'), ('$', 'TOP - Tongan Paʻanga (T$)'), ('$', 'BND - Brunei Dollar ($)'), ('₼', 'TMT - Turkmenistani Manat (₼)'), ('Sh', 'TZS - Tanzanian Shilling (Sh)'), ('UGX', 'UGX - Ugandan Shilling (UGX)'), ('₴', 'UAH - Ukrainian Hryvnia (₴)'), ('Sh', 'KES - Kenyan Shilling (Sh)'), ('$', 'VUV - Vanuatu Vatu (VUV)'), ('₫', 'VND - Vietnamese đồng (₫)'), ('Kz', 'AOA - Angolan Kwanza (Kz)'), ('Fr', 'XAF - CFA Franc BEAC (Fr)'), ('₣', 'XPF - CFP Franc (₣)'), ('$', 'LRD - Liberian Dollar ($)'), ('₣', 'XOF - CFA Franc BCEAO (₣)'), ('$', 'SLL - Sierra Leonean Leone ($)')], default='USD', max_length=3),
        ),
    ]
