# Generated by Django 5.0.7 on 2024-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0048_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='primary_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
