# Generated by Django 5.0.7 on 2024-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0049_settings_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='button_bg_color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='button_color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='heading_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
