# Generated by Django 5.0.7 on 2024-10-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0051_remove_settings_button_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='button_bg_color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='heading_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
