# Generated by Django 5.0.7 on 2024-10-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0052_settings_button_bg_color_settings_heading_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='additional_css',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
