# Generated by Django 5.0.7 on 2024-10-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0053_settings_additional_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='additional_css',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
    ]
