# Generated by Django 5.0.7 on 2024-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0055_alter_settings_additional_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='fb_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='settings',
            name='insta_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='settings',
            name='linkedin_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='settings',
            name='pinterest_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='settings',
            name='twiter_link',
            field=models.CharField(default='', max_length=240),
        ),
    ]
