# Generated by Django 5.0.7 on 2024-10-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0056_settings_fb_link_settings_insta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='copyright',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='insta_link',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pinterest_link',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twiter_link',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
