# Generated by Django 5.0.7 on 2024-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0057_alter_settings_copyright_alter_settings_insta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='settings',
            name='button_bg_color',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='button_color',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fb_link',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='settings',
            name='heading_color',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='store_address',
            field=models.TextField(blank=True),
        ),
    ]
